# Generated by Django 4.2.10 on 2024-02-19 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardgame', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='color',
        ),
        migrations.RemoveField(
            model_name='card',
            name='value',
        ),
        migrations.RemoveField(
            model_name='game',
            name='deck',
        ),
        migrations.AddField(
            model_name='card',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='suit',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='player',
            name='wallet',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='current_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cardgame.player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='cards',
            field=models.ManyToManyField(related_name='players_cards', to='cardgame.card'),
        ),
        migrations.CreateModel(
            name='Hand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cardgame.player')),
            ],
        ),
    ]
